[theme]
base = "light"
primaryColor = "#12796f"
backgroundColor = "#f7f9f8"
secondaryBackgroundColor = "#eaf0ee"
textColor = "#183d42"
font = "sans serif"

[server]
maxUploadSize = 64

[browser]
gatherUsageStats = false
